# Generated by Django 5.0 on 2024-03-01 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('menid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('menname', models.TextField(max_length=225)),
                ('menroomno', models.CharField(default='sk2', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stuname', models.TextField(max_length=225)),
                ('stuemail', models.CharField(max_length=225)),
                ('stuage', models.PositiveSmallIntegerField(default=0)),
                ('stumentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmodule.mentor')),
            ],
        ),
    ]
